"""Tests for the bridge engine, new platforms, skill export, plugins (WS6)."""
from click.testing import CliRunner

from stato.bridge.engine import build_bridge_content, write_bridge
from stato.bridge.platforms import (
    BUILTIN_PLATFORMS,
    all_platform_names,
    resolve_platform,
)
from stato.cli import main
from stato.core.state_manager import init_project, write_module
from tests.fixtures import VALID_PLAN, VALID_QC_SKILL


def _project(tmp_path):
    project = init_project(tmp_path)
    write_module(project, "skills/qc.py", VALID_QC_SKILL)
    write_module(project, "plan.py", VALID_PLAN)
    return project


def test_all_builtin_specs_generate(tmp_path):
    project = _project(tmp_path)
    for name, spec in BUILTIN_PLATFORMS.items():
        path, action = write_bridge(project, spec, force=True)
        assert path.exists(), name
        content = path.read_text()
        assert "qc_filtering" in content, name
        assert "Generated by stato" in content, name


def test_mdc_frontmatter_first_line(tmp_path):
    project = _project(tmp_path)
    content = build_bridge_content(
        project / ".stato", BUILTIN_PLATFORMS["cursor"]
    )
    lines = content.splitlines()
    assert lines[0] == "---"
    close = lines[1:].index("---") + 1
    frontmatter = lines[1:close]
    assert any(line.startswith("description:") for line in frontmatter)
    assert "alwaysApply: true" in frontmatter
    # marker comes after frontmatter, not before
    assert "Generated by stato" in lines[close + 1]


def test_agents_is_alias_target_for_codex():
    assert resolve_platform("codex") is BUILTIN_PLATFORMS["agents"]


def test_unknown_platform_resolves_none():
    assert resolve_platform("does-not-exist") is None


def test_all_platform_names_excludes_legacy_by_default():
    names = all_platform_names()
    assert "cursor-legacy" not in names
    assert "agents" in names
    names_with = all_platform_names(include_legacy=True)
    assert "cursor-legacy" in names_with


def test_plan_summary_in_bridge(tmp_path):
    project = _project(tmp_path)
    content = build_bridge_content(project / ".stato", BUILTIN_PLATFORMS["agents"])
    assert "## Current Plan" in content
    assert "steps complete" in content


def test_bridge_rules_count_consistent(tmp_path):
    project = _project(tmp_path)
    for name in ("agents", "claude", "cursor", "copilot", "gemini"):
        content = build_bridge_content(project / ".stato", BUILTIN_PLATFORMS[name])
        rule_lines = [
            line for line in content.splitlines()
            if line[:2].rstrip(".").isdigit() or (line and line[0].isdigit() and ". " in line[:4])
        ]
        assert len(rule_lines) == 8, f"{name} has {len(rule_lines)} rules"


def test_skill_export(tmp_path):
    project = _project(tmp_path)
    from stato.bridge.skill_export import export_skill

    path, action = export_skill(project, force=True)
    assert action in ("created", "overwritten")
    assert path.name == "SKILL.md"
    assert ".claude/skills/" in str(path)
    content = path.read_text()
    assert content.startswith("---\n")
    assert "name: stato-" in content
    assert "description: " in content
    assert "qc_filtering" in content


def test_skill_export_via_cli(tmp_path):
    _project(tmp_path)
    runner = CliRunner()
    result = runner.invoke(
        main, ["bridge", "--platform", "skill", "--path", str(tmp_path), "--force"]
    )
    assert result.exit_code == 0
    skills_dir = tmp_path / ".claude" / "skills"
    assert list(skills_dir.rglob("SKILL.md"))


def test_plugin_platform_loaded_when_enabled(tmp_path, monkeypatch):
    monkeypatch.setenv("STATO_CONFIG_DIR", str(tmp_path / "conf"))
    conf = tmp_path / "conf"
    (conf / "bridges").mkdir(parents=True)
    (conf / "config.toml").write_text("[plugins]\nenabled = true\n")
    (conf / "bridges" / "zed.py").write_text(
        'PLATFORM_SPEC = {"key": "zed", "output_path": ".rules", '
        '"title": "# Zed Rules"}\n'
    )
    spec = resolve_platform("zed")
    assert spec is not None
    assert spec.output_path == ".rules"

    _project(tmp_path / "proj")
    path, _ = write_bridge(tmp_path / "proj", spec, force=True)
    assert (tmp_path / "proj" / ".rules").exists()
    assert "# Zed Rules" in path.read_text()


def test_plugins_disabled_by_default(tmp_path, monkeypatch):
    monkeypatch.setenv("STATO_CONFIG_DIR", str(tmp_path / "conf"))
    conf = tmp_path / "conf"
    (conf / "bridges").mkdir(parents=True)
    # no config.toml -> plugins disabled
    (conf / "bridges" / "zed.py").write_text(
        'PLATFORM_SPEC = {"key": "zed", "output_path": ".rules"}\n'
    )
    assert resolve_platform("zed") is None


def test_broken_plugin_does_not_crash(tmp_path, monkeypatch):
    monkeypatch.setenv("STATO_CONFIG_DIR", str(tmp_path / "conf"))
    conf = tmp_path / "conf"
    (conf / "bridges").mkdir(parents=True)
    (conf / "config.toml").write_text("[plugins]\nenabled = true\n")
    (conf / "bridges" / "broken.py").write_text("raise RuntimeError('boom')\n")
    (conf / "bridges" / "good.py").write_text(
        'PLATFORM_SPEC = {"key": "good", "output_path": "GOOD.md"}\n'
    )
    assert resolve_platform("good") is not None
    assert resolve_platform("broken") is None
