"""Team assembly — generate expertise-scoped subagents from a team spec.

`stato team assemble` reads a team.toml (default: .stato/team.toml), slices each
role's skills out of .stato/, and writes a per-role subagent definition. The
value is scoping: each subagent carries only its own skills, keeping its context
window focused. Handoffs are rendered as prose, not an enforced protocol — the
orchestrating agent still decides who runs when.

Output formats (--format, repeatable, or "all"), each matching the tool's
native subagent format:
  claude -> .claude/agents/<role>.md      (YAML frontmatter + body)
  gemini -> .gemini/agents/<role>.md      (YAML frontmatter + body; Gemini's own
                                           tool names, so team tools are omitted)
  codex  -> .codex/agents/<role>.toml     (TOML; prompt in developer_instructions)
  sdk    -> .stato/team/<role>.agent.json (Claude Agent SDK agent config)
"""
from __future__ import annotations

import json
from dataclasses import dataclass, field
from pathlib import Path

from stato.bridge.engine import _count_lessons
from stato.core.composer import (
    _discover_modules,
    _get_depends_on,
    _module_provides,
)
from stato.core.module import ModuleType

TEAM_MARKER = "Generated by stato team assemble"
DEFAULT_TEAM_PATH = ".stato/team.toml"

FORMAT_DIRS = {
    "claude": ".claude/agents",
    "codex": ".codex/agents",
    "gemini": ".gemini/agents",
    "sdk": ".stato/team",
}
ALL_FORMATS = list(FORMAT_DIRS.keys())


@dataclass
class AgentSpec:
    role: str
    description: str
    skills: list[str]
    model: str | None = None
    tools: list[str] = field(default_factory=list)
    with_deps: bool = False
    handoff: str = ""


@dataclass
class TeamSpec:
    name: str
    description: str
    agents: list[AgentSpec]


class TeamSpecError(ValueError):
    """Raised when a team.toml is malformed or references missing skills."""


# --- Parsing ---------------------------------------------------------------

def parse_team_spec(path: Path) -> TeamSpec:
    import tomli

    if not path.exists():
        raise TeamSpecError(f"Team spec not found: {path}")
    try:
        data = tomli.loads(path.read_text())
    except tomli.TOMLDecodeError as e:
        raise TeamSpecError(f"Invalid TOML in {path}: {e}") from e

    team = data.get("team", {})
    agents_table = data.get("agents", {})
    if not isinstance(agents_table, dict) or not agents_table:
        raise TeamSpecError(
            f"{path} has no [agents.<role>] tables — define at least one agent"
        )

    agents = []
    for role, info in agents_table.items():
        if not isinstance(info, dict):
            raise TeamSpecError(f"Agent '{role}' must be a [agents.{role}] table")
        if "description" not in info:
            raise TeamSpecError(f"Agent '{role}' is missing required 'description'")
        skills = info.get("skills")
        if not isinstance(skills, list) or not skills:
            raise TeamSpecError(
                f"Agent '{role}' needs a non-empty 'skills' list"
            )
        tools = info.get("tools", [])
        if tools and not isinstance(tools, list):
            raise TeamSpecError(f"Agent '{role}': 'tools' must be a list")
        agents.append(AgentSpec(
            role=role,
            description=info["description"],
            skills=[str(s) for s in skills],
            model=info.get("model"),
            tools=[str(t) for t in tools],
            with_deps=bool(info.get("with_deps", False)),
            handoff=info.get("handoff", ""),
        ))

    return TeamSpec(
        name=team.get("name", ""),
        description=team.get("description", ""),
        agents=agents,
    )


# --- Skill resolution ------------------------------------------------------

def _skill_key(mod: dict) -> set[str]:
    """The names a skill can be referenced by: its `name` field and file stem."""
    keys = {Path(str(mod["rel_path"])).stem}
    cls = mod["namespace"].get(mod["class_name"]) if mod.get("namespace") else None
    if cls is not None:
        name = getattr(cls, "name", None)
        if name:
            keys.add(str(name))
    return keys


def resolve_agent_skills(stato_dir: Path, agent: AgentSpec) -> list[dict]:
    """Return the skill module dicts for an agent. Raises on unknown skills."""
    all_modules = _discover_modules(stato_dir)
    skills = [m for m in all_modules if m["module_type"] == ModuleType.SKILL]

    selected: list[dict] = []
    selected_keys: set[str] = set()
    for wanted in agent.skills:
        match = next((s for s in skills if wanted in _skill_key(s)), None)
        if match is None:
            available = sorted({k for s in skills for k in _skill_key(s)})
            raise TeamSpecError(
                f"Agent '{agent.role}' references unknown skill '{wanted}'. "
                f"Available skills: {', '.join(available) or '(none)'}"
            )
        key = str(match["rel_path"])
        if key not in selected_keys:
            selected.append(match)
            selected_keys.add(key)

    if agent.with_deps:
        # Pull dependency skills that live in the project.
        queue = list(selected)
        while queue:
            mod = queue.pop(0)
            for dep in _get_depends_on(mod):
                for cand in skills:
                    if _module_provides(cand, dep) and str(cand["rel_path"]) not in selected_keys:
                        selected.append(cand)
                        selected_keys.add(str(cand["rel_path"]))
                        queue.append(cand)

    return selected


# --- Rendering -------------------------------------------------------------

def _skill_table(skills: list[dict]) -> list[str]:
    lines = ["| Skill | Version | Key parameters | Lessons |", "|---|---|---|---|"]
    for s in skills:
        cls = s["namespace"].get(s["class_name"])
        name = getattr(cls, "name", s["class_name"])
        version = getattr(cls, "version", "-")
        params = getattr(cls, "default_params", {}) or {}
        param_str = ", ".join(f"{k}={v}" for k, v in list(params.items())[:3]) or "-"
        lines.append(f"| {name} | v{version} | {param_str} | {_count_lessons(cls)} lessons |")
    return lines


def _agent_body(team: TeamSpec, agent: AgentSpec, skills: list[dict],
                inline: bool = False) -> str:
    from stato.core.summarize import render_summary, summarize_module

    team_name = team.name or "this project"
    lines = [f"You are the **{agent.role}** on the {team_name} team."]
    if agent.description:
        lines += ["", agent.description]
    lines += ["", "## Your expertise", ""]
    lines += _skill_table(skills)
    lines += [""]
    if inline:
        # Full skill source inlined (for environments without the stato MCP server).
        for s in skills:
            src = s["full_path"].read_text() if s.get("full_path") else ""
            lines += [f"### {s['rel_path']}", "```python", src.rstrip(), "```", ""]
    else:
        # Default: lessons INDEX per skill + pull-on-demand (progressive
        # disclosure). Keeps the subagent light; it pulls the exact lesson it
        # needs via the stato MCP server (stato_get_skill_section) or by reading
        # the specific section of .stato/skills/<name>.py.
        for s in skills:
            summary = summarize_module(s["full_path"].read_text()) if s.get("full_path") else None
            if summary is not None:
                lines += [render_summary(summary), ""]
        lines += ["Pull a lesson's full text on demand via the stato MCP tool "
                  "`stato_get_skill_section(skill, id)`, or read that section of "
                  "`.stato/skills/<name>.py`. Don't load whole skills up front."]
    if agent.handoff:
        lines += ["", "## Handoff", "", agent.handoff]
    lines += [
        "", "## Working rules",
        "1. Read `.stato/plan.py` for current progress before starting.",
        "2. Use only your assigned skills; request another role for out-of-scope work.",
        "3. After meaningful work, update `.stato/` and run `stato validate .stato/`.",
    ]
    return "\n".join(lines) + "\n"


def render_claude_agent(team: TeamSpec, agent: AgentSpec, skills: list[dict], inline: bool = False) -> str:
    """Claude Code subagent: .claude/agents/<role>.md.

    Format: YAML frontmatter (name/description/model/tools) + markdown body.
    Claude tool names (Read, Edit, Bash) map 1:1 to team.toml `tools`.
    """
    lines = ["---", f"name: {agent.role}", f"description: {agent.description}"]
    if agent.model:
        lines.append(f"model: {agent.model}")
    if agent.tools:
        lines.append(f"tools: {', '.join(agent.tools)}")
    lines.append("---")
    return (
        "\n".join(lines)
        + f"\n<!-- {TEAM_MARKER}. Regenerate: stato team assemble -->\n\n"
        + _agent_body(team, agent, skills, inline)
    )


def render_gemini_agent(team: TeamSpec, agent: AgentSpec, skills: list[dict], inline: bool = False) -> str:
    """Gemini CLI subagent: .gemini/agents/<role>.md.

    Format: YAML frontmatter + markdown body (system prompt), like Claude's.
    Fields verified vs Gemini CLI docs: name, description, optional model,
    temperature, max_turns. `tools` is intentionally omitted — Gemini uses its
    own tool names (read_file, grep_search, ...), so team.toml's Claude-style
    tools would be invalid here; scope is enforced via the body instead.
    """
    lines = ["---", f"name: {agent.role}", f"description: {agent.description}"]
    if agent.model:
        lines.append(f"model: {agent.model}")
    lines.append("---")
    return (
        "\n".join(lines)
        + f"\n<!-- {TEAM_MARKER}. Regenerate: stato team assemble -->\n\n"
        + _agent_body(team, agent, skills, inline)
    )


def render_codex_agent(team: TeamSpec, agent: AgentSpec, skills: list[dict], inline: bool = False) -> str:
    """Codex CLI subagent: .codex/agents/<role>.toml.

    Format verified vs Codex docs: TOML with name/description/
    developer_instructions (the system prompt as a string), optional model.
    Codex has no simple tools allowlist, so team.toml `tools` are dropped.
    """
    import tomli_w

    config: dict = {
        "name": agent.role,
        "description": agent.description,
        "developer_instructions": _agent_body(team, agent, skills, inline),
    }
    if agent.model:
        config["model"] = agent.model
    return (
        f"# {TEAM_MARKER}. Regenerate: stato team assemble\n"
        + tomli_w.dumps(config)
    )


def render_sdk_agent(team: TeamSpec, agent: AgentSpec, skills: list[dict], inline: bool = False) -> str:
    """Claude Agent SDK agent config (JSON)."""
    config = {
        "name": agent.role,
        "description": agent.description,
        "prompt": _agent_body(team, agent, skills, inline),
        "_generated_by": TEAM_MARKER,
    }
    if agent.model:
        config["model"] = agent.model
    if agent.tools:
        config["tools"] = agent.tools
    return json.dumps(config, indent=2) + "\n"


_RENDERERS = {
    "claude": render_claude_agent,
    "gemini": render_gemini_agent,
    "codex": render_codex_agent,
    "sdk": render_sdk_agent,
}


# --- Orchestration ---------------------------------------------------------

_FORMAT_EXT = {"claude": ".md", "gemini": ".md", "codex": ".toml", "sdk": ".agent.json"}


def _output_path(project_dir: Path, fmt: str, role: str) -> Path:
    return project_dir / FORMAT_DIRS[fmt] / f"{role}{_FORMAT_EXT[fmt]}"


def _is_stato_owned(path: Path) -> bool:
    if not path.exists():
        return True  # nothing to protect
    try:
        return TEAM_MARKER in path.read_text()
    except OSError:
        return False


def assemble(
    project_dir: Path,
    team_path: Path | None = None,
    formats: list[str] | None = None,
    force: bool = False,
    dry_run: bool = False,
    inline: bool = False,
) -> list[tuple[Path, str]]:
    """Generate subagent files for every role. Returns [(path, action), ...].

    action ∈ {created, overwritten, skipped, would-write}.
    """
    project_dir = Path(project_dir)
    stato_dir = project_dir / ".stato"
    team_path = team_path or (project_dir / DEFAULT_TEAM_PATH)
    formats = formats or ["claude"]

    team = parse_team_spec(team_path)
    # Resolve all agents first so an unknown skill fails before any write.
    resolved = {a.role: resolve_agent_skills(stato_dir, a) for a in team.agents}

    results: list[tuple[Path, str]] = []
    for agent in team.agents:
        skills = resolved[agent.role]
        for fmt in formats:
            path = _output_path(project_dir, fmt, agent.role)
            content = _RENDERERS[fmt](team, agent, skills, inline)
            existed = path.exists()
            if existed and not force and not _is_stato_owned(path):
                results.append((path, "skipped"))
                continue
            if dry_run:
                results.append((path, "would-write"))
                continue
            path.parent.mkdir(parents=True, exist_ok=True)
            path.write_text(content)
            results.append((path, "overwritten" if existed else "created"))
    return results
